### ISSUE TITLE
Como administrador, necesito un módulo para gestionar el inventario.

### ISSUE THREAD

**Issue by Jgaray3008** [Berlincordero/FKYBSOFTWARE#34]
Escenario 1
• Criterio de Aceptación: El sistema debe permitir registrar nuevos productos en el inventario.
• Contexto: Usuario en módulo de inventario.
• Evento: Registra nuevo producto.
• Resultado: Producto registrado y reflejado en el inventario.

Escenario 2
• Criterio de Aceptación: El sistema debe permitir consultar el stock de productos disponibles.
• Contexto: Usuario en módulo de inventario.
• Evento: Consulta stock de productos.
• Resultado: Listado de productos con stock disponible.

Escenario 3
• Criterio de Aceptación: El sistema debe permitir generar un reporte de inventario en formato PDF y XML.
• Contexto: Usuario en módulo de inventario.
• Evento: Genera reporte de inventario.
• Resultado: Reporte generado y exportable en formato PDF y XML.

**Comment by Berlincordero** [comment]
se crea un modulo para gestionar el inventario en este caso el de productos
